// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnD15wofiCJVN7qJIHiRIGmCifL_PTAyw',
    appId: '1:116426777290:web:6978353751e8a02f7f4a33',
    messagingSenderId: '116426777290',
    projectId: 'gustavo-2-0',
    authDomain: 'gustavo-2-0.firebaseapp.com',
    storageBucket: 'gustavo-2-0.appspot.com',
    measurementId: 'G-L8GWXXJXS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy-Q471ZsqhsuYWfSjhon7R6liqLuawgg',
    appId: '1:116426777290:android:fff8f8d88e32e2907f4a33',
    messagingSenderId: '116426777290',
    projectId: 'gustavo-2-0',
    storageBucket: 'gustavo-2-0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhrYbfVPpCwU7EdmtZVeYO2HMv6wBvWps',
    appId: '1:116426777290:ios:390f148ac405f1607f4a33',
    messagingSenderId: '116426777290',
    projectId: 'gustavo-2-0',
    storageBucket: 'gustavo-2-0.appspot.com',
    iosClientId: '116426777290-nfb4coda0mb574rhl5p50n66fk966mqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.gustavo20',
  );
}
